/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ucsc.groupone.frameworkide;

import com.ucsc.groupone.models.FileSystemModel;
import com.ucsc.groupone.dialogs.CreateNewModel;
import com.ucsc.groupone.dialogs.CreateProject;
import com.ucsc.groupone.models.ClassifierModel;
import com.ucsc.groupone.mouseListeners.ModelOptionsPopUpClickListener;
import com.ucsc.groupone.utils.SystemConstants;
import com.ucsc.groupone.utils.SystemVariables;
import java.awt.Color;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Attr;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 *
 * @author hashan
 */
public class MasterFrame extends javax.swing.JFrame implements MouseMotionListener, MouseListener, Runnable {

    /**
     * Creates new form MasterFrame
     */
    ClassifierModel modelIcon = null;
    Point startPoint;
    Thread thread = null;
    JTree tree;
    DefaultMutableTreeNode root;
    DefaultTreeModel model;

    public MasterFrame() {
        initComponents();
        start();
        enableTrainButtons(false);
        fileStructureTree.setModel(new FileSystemModel(new File(SystemVariables.projectRootFolder)));
    }

    public MasterFrame(ClassifierModel modelIcon, String projectRootFolder) {
        initComponents();
        start();
        this.modelIcon = modelIcon;
        SystemVariables.projectRootFolder = projectRootFolder;
        if (modelIcon == null) {
            enableTrainButtons(false);
        } else {
            enableTrainButtons(true);
        }
        fileStructureTree.setModel(new FileSystemModel(new File(SystemVariables.projectRootFolder)));
        loadModelOnWorkspace();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolBar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        predictClassifierButton = new javax.swing.JButton();
        trainClassifierButton = new javax.swing.JButton();
        testClassifierButton = new javax.swing.JButton();
        leftShortcuts = new javax.swing.JPanel();
        createPathPlanButton = new javax.swing.JButton();
        createRoboticArmInterfaceButton = new javax.swing.JButton();
        createModelButton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        filesFrame = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        fileStructureTree = new javax.swing.JTree();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        propertyWindow = new javax.swing.JTable();
        workspacePanel = new javax.swing.JPanel();
        mainMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        createProjectFileMenu = new javax.swing.JMenuItem();
        openProjectFileMenu = new javax.swing.JMenuItem();
        closeProject = new javax.swing.JMenuItem();
        saveProjectFileMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitFileMenu = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        toolsMenu = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Framework IDE");
        setIconImage(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/main-icon.png").getImage());

        toolBar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        toolBar.setPreferredSize(new java.awt.Dimension(757, 30));

        jLabel1.setFont(new java.awt.Font("Fira Code", 0, 13)); // NOI18N
        jLabel1.setText("MainProject > Model > Tensorflow > ObjectDetectionNotebook.ipynb");

        predictClassifierButton.setIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/predict-data.png")); // NOI18N
        predictClassifierButton.setBorder(null);
        predictClassifierButton.setBorderPainted(false);
        predictClassifierButton.setContentAreaFilled(false);
        predictClassifierButton.setFocusPainted(false);
        predictClassifierButton.setPreferredSize(new java.awt.Dimension(540, 524));
        predictClassifierButton.setRolloverIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/predict-data-black.png")); // NOI18N
        predictClassifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predictClassifierButtonActionPerformed(evt);
            }
        });

        trainClassifierButton.setIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/train-data.png")); // NOI18N
        trainClassifierButton.setBorder(null);
        trainClassifierButton.setBorderPainted(false);
        trainClassifierButton.setContentAreaFilled(false);
        trainClassifierButton.setIconTextGap(0);
        trainClassifierButton.setPreferredSize(new java.awt.Dimension(540, 524));
        trainClassifierButton.setRolloverIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/train-data-black.png")); // NOI18N
        trainClassifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainClassifierButtonActionPerformed(evt);
            }
        });

        testClassifierButton.setIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/test-data.png")); // NOI18N
        testClassifierButton.setBorder(null);
        testClassifierButton.setBorderPainted(false);
        testClassifierButton.setContentAreaFilled(false);
        testClassifierButton.setFocusPainted(false);
        testClassifierButton.setPreferredSize(new java.awt.Dimension(540, 524));
        testClassifierButton.setRolloverIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/test-data-black.png")); // NOI18N
        testClassifierButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testClassifierButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toolBarLayout = new javax.swing.GroupLayout(toolBar);
        toolBar.setLayout(toolBarLayout);
        toolBarLayout.setHorizontalGroup(
            toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trainClassifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(testClassifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(predictClassifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        toolBarLayout.setVerticalGroup(
            toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
            .addComponent(predictClassifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(toolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainClassifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(testClassifierButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        leftShortcuts.setBackground(new java.awt.Color(204, 204, 204));
        leftShortcuts.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(153, 153, 153)));
        leftShortcuts.setInheritsPopupMenu(true);
        leftShortcuts.setPreferredSize(new java.awt.Dimension(80, 27));

        createPathPlanButton.setIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/path-planning.png")); // NOI18N
        createPathPlanButton.setToolTipText("Create a Path Plan");
        createPathPlanButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        createPathPlanButton.setContentAreaFilled(false);
        createPathPlanButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createPathPlanButton.setPreferredSize(new java.awt.Dimension(80, 27));
        createPathPlanButton.setRolloverIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/path-planning-black.png")); // NOI18N
        createPathPlanButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createPathPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPathPlanButtonActionPerformed(evt);
            }
        });

        createRoboticArmInterfaceButton.setIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/robotic-arm.png")); // NOI18N
        createRoboticArmInterfaceButton.setToolTipText("Create a Robotic Arm Interface");
        createRoboticArmInterfaceButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        createRoboticArmInterfaceButton.setContentAreaFilled(false);
        createRoboticArmInterfaceButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createRoboticArmInterfaceButton.setPreferredSize(new java.awt.Dimension(80, 27));
        createRoboticArmInterfaceButton.setRolloverIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/robotic-arm-black.png")); // NOI18N
        createRoboticArmInterfaceButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createRoboticArmInterfaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRoboticArmInterfaceButtonActionPerformed(evt);
            }
        });

        createModelButton.setIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/model.png")); // NOI18N
        createModelButton.setToolTipText("Create a Model");
        createModelButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        createModelButton.setContentAreaFilled(false);
        createModelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        createModelButton.setPreferredSize(new java.awt.Dimension(80, 27));
        createModelButton.setRolloverIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/model-black.png")); // NOI18N
        createModelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        createModelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createModelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftShortcutsLayout = new javax.swing.GroupLayout(leftShortcuts);
        leftShortcuts.setLayout(leftShortcutsLayout);
        leftShortcutsLayout.setHorizontalGroup(
            leftShortcutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftShortcutsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(leftShortcutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createPathPlanButton, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(createRoboticArmInterfaceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createModelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        leftShortcutsLayout.setVerticalGroup(
            leftShortcutsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftShortcutsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createModelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createPathPlanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createRoboticArmInterfaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        jInternalFrame1.setBackground(new java.awt.Color(51, 51, 51));
        jInternalFrame1.setTitle("Log");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jInternalFrame1.setFrameIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/log-icon.png")); // NOI18N
        jInternalFrame1.setName(""); // NOI18N
        try {
            jInternalFrame1.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrame1.setVisible(true);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        logArea.setEditable(false);
        logArea.setBackground(new java.awt.Color(255, 255, 255));
        logArea.setColumns(20);
        logArea.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        logArea.setForeground(new java.awt.Color(51, 51, 51));
        logArea.setLineWrap(true);
        logArea.setRows(5);
        logArea.setToolTipText("");
        logArea.setBorder(null);
        logArea.setFocusable(false);
        jScrollPane1.setViewportView(logArea);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(153, 153, 153)));

        filesFrame.setTitle("Files");
        filesFrame.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        filesFrame.setFrameIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/file-icon.png")); // NOI18N
        try {
            filesFrame.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        filesFrame.setVisible(true);

        fileStructureTree.setModel(new FileSystemModel(new File("/home/hashan/FrameworkIDE")));
        fileStructureTree.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jScrollPane2.setViewportView(fileStructureTree);

        javax.swing.GroupLayout filesFrameLayout = new javax.swing.GroupLayout(filesFrame.getContentPane());
        filesFrame.getContentPane().setLayout(filesFrameLayout);
        filesFrameLayout.setHorizontalGroup(
            filesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
        );
        filesFrameLayout.setVerticalGroup(
            filesFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filesFrameLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );

        jInternalFrame3.setTitle("Properties");
        jInternalFrame3.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        jInternalFrame3.setFrameIcon(new javax.swing.ImageIcon("/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/properties-icon.png")); // NOI18N
        jInternalFrame3.setOpaque(false);
        try {
            jInternalFrame3.setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        jInternalFrame3.setVisible(true);

        propertyWindow.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        propertyWindow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Property", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(propertyWindow);

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(filesFrame)
            .addComponent(jInternalFrame3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(filesFrame)
                .addGap(0, 0, 0)
                .addComponent(jInternalFrame3)
                .addGap(0, 0, 0))
        );

        try {
            filesFrame.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        try {
            jInternalFrame3.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        workspacePanel.setBackground(new java.awt.Color(255, 255, 255));
        workspacePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                workspacePanelMouseClicked(evt);
            }
        });

        mainMenu.setName(""); // NOI18N

        fileMenu.setText("File");
        fileMenu.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        createProjectFileMenu.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N
        createProjectFileMenu.setText("Create Project");
        createProjectFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectFileMenuActionPerformed(evt);
            }
        });
        fileMenu.add(createProjectFileMenu);

        openProjectFileMenu.setText("Open Project");
        fileMenu.add(openProjectFileMenu);

        closeProject.setText("Close Project");
        fileMenu.add(closeProject);

        saveProjectFileMenu.setText("Save Project");
        saveProjectFileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProjectFileMenuActionPerformed(evt);
            }
        });
        fileMenu.add(saveProjectFileMenu);
        fileMenu.add(jSeparator1);

        exitFileMenu.setText("Exit");
        fileMenu.add(exitFileMenu);

        mainMenu.add(fileMenu);

        editMenu.setText("Edit");
        editMenu.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        jMenuItem1.setText("Undo");
        editMenu.add(jMenuItem1);

        jMenuItem2.setText("Redo");
        editMenu.add(jMenuItem2);

        jMenuItem3.setText("Cut");
        editMenu.add(jMenuItem3);

        jMenuItem4.setText("Copy");
        editMenu.add(jMenuItem4);

        jMenuItem5.setText("Paste");
        editMenu.add(jMenuItem5);

        jMenuItem6.setText("Select All");
        editMenu.add(jMenuItem6);

        jMenuItem7.setText("Find");
        editMenu.add(jMenuItem7);

        jMenuItem8.setText("Replace");
        editMenu.add(jMenuItem8);

        mainMenu.add(editMenu);

        viewMenu.setText("View");
        viewMenu.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        jMenuItem9.setText("Full Screen");
        viewMenu.add(jMenuItem9);

        jMenuItem10.setText("Debug Console");
        viewMenu.add(jMenuItem10);

        jMenuItem11.setText("Terminal");
        viewMenu.add(jMenuItem11);

        jMenuItem12.setText("Zoom In");
        viewMenu.add(jMenuItem12);

        jMenuItem13.setText("Zoom Out");
        viewMenu.add(jMenuItem13);

        mainMenu.add(viewMenu);

        toolsMenu.setText("Tools");
        toolsMenu.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        jMenuItem14.setText("XML to CSV");
        toolsMenu.add(jMenuItem14);

        jMenuItem15.setText("CSV to .record");
        toolsMenu.add(jMenuItem15);

        jMenuItem16.setText("LabelIMG");
        toolsMenu.add(jMenuItem16);

        mainMenu.add(toolsMenu);

        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Fira Code", 0, 12)); // NOI18N

        jMenuItem17.setText("Documentation");
        helpMenu.add(jMenuItem17);

        jMenuItem18.setText("Keyboard Shortcuts");
        helpMenu.add(jMenuItem18);

        jMenuItem19.setText("Submit Feedback");
        helpMenu.add(jMenuItem19);

        jMenuItem20.setText("Report a Problem");
        helpMenu.add(jMenuItem20);

        jMenuItem21.setText("About This");
        helpMenu.add(jMenuItem21);

        mainMenu.add(helpMenu);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 992, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftShortcuts, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workspacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(toolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftShortcuts, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(workspacePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        try {
            jInternalFrame1.setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void predictClassifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predictClassifierButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_predictClassifierButtonActionPerformed

    private void testClassifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testClassifierButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testClassifierButtonActionPerformed

    private void createPathPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPathPlanButtonActionPerformed
        logText("Path Plannning Clicked");
    }//GEN-LAST:event_createPathPlanButtonActionPerformed

    private void createModelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createModelButtonActionPerformed
        if (modelIcon != null) {
            logText(SystemConstants.MODEL_AVAILABLE);
            return;
        }
        logText("Model Clicked");
        CreateNewModel createNewModel = new CreateNewModel(this, true);
        HashMap<String, String> returnValues = createNewModel.showDialog();

        if (returnValues.isEmpty()) {
            logText(SystemConstants.MODEL_NOT_CREATED);
        } else if (returnValues.size() == 6) {
            createModelOnWorkspace(returnValues);
            createModelFileInFolderStructure(returnValues);
        } else {
            logText(SystemConstants.INVALID_HASHMAP);
        }
    }//GEN-LAST:event_createModelButtonActionPerformed

    private void createRoboticArmInterfaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRoboticArmInterfaceButtonActionPerformed
        logText("Robotic Arm Interface Clicked");
    }//GEN-LAST:event_createRoboticArmInterfaceButtonActionPerformed

    private void workspacePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_workspacePanelMouseClicked
//        modelIcon.requestFocusInWindow();
    }//GEN-LAST:event_workspacePanelMouseClicked

    private void trainClassifierButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainClassifierButtonActionPerformed

        logText("Please Wait Until The Testing Is Finished");
        logText("Starting Testing...");

        String command = "python3 /home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/com/ucsc/groupone/python/Predict.py "
                + modelIcon.getFigPath() + " " + modelIcon.getTiPath() + " "
                + modelIcon.getOiPath() + " " + modelIcon.getCfPath();

        try {
            String line;
            Process process = Runtime.getRuntime().exec(command);
//            ProcessBuilder pb = new ProcessBuilder("python3", "/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/com/ucsc/groupone/python/Predict.py",
//            modelIcon.getFigPath(), modelIcon.getTiPath(), modelIcon.getOiPath(), modelIcon.getCfPath());
//            pb.redirectOutput(ProcessBuilder.Redirect.INHERIT);
//            Process process = pb.start();
            process.waitFor();
            BufferedReader error = new BufferedReader(new InputStreamReader(process.getErrorStream()));
            while ((line = error.readLine()) != null) {
//                logText(line);
            }
            error.close();

            BufferedReader input = new BufferedReader(new InputStreamReader(process.getInputStream()));
            while ((line = input.readLine()) != null) {
//                logText(line);
            }

            input.close();

            OutputStream outputStream = process.getOutputStream();
            PrintStream printStream = new PrintStream(outputStream);
            printStream.println();
            printStream.flush();
            printStream.close();
            logText("Images Created At Output Directory");
            logText("Testing Completed");
        } catch (IOException ex) {
            Logger.getLogger(MasterFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(MasterFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_trainClassifierButtonActionPerformed

    private void saveProjectFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProjectFileMenuActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Specify A File To Save");
        int userSelection = jfc.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            PrintWriter file = null;
            try {
                File fileToSave = jfc.getSelectedFile();
//                System.out.println("Save file as : " + fileToSave.getPath());
                file = new PrintWriter(fileToSave);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MasterFrame.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                file.close();
            }
        }
    }//GEN-LAST:event_saveProjectFileMenuActionPerformed

    private void createProjectFileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectFileMenuActionPerformed
        CreateProject cp = new CreateProject(this, rootPaneCheckingEnabled);
        String returnedValue = cp.showDialog();
        if (returnedValue != null) {
            logText(returnedValue);
        }
        fileStructureTree.setModel(new FileSystemModel(new File(SystemVariables.projectRootFolder)));
    }//GEN-LAST:event_createProjectFileMenuActionPerformed

//    public void clearTree(JTree tree) {
//    DefaultTreeModel model = (DefaultTreeModel)tree.getModel();
//DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
//model.reload(root);
//}
    private void configure() {
        File fileRoot = new File("/home/hashan");

        DefaultMutableTreeNode root = new DefaultMutableTreeNode(fileRoot);
        DefaultTreeModel model = new DefaultTreeModel(root);

        File[] subItems = fileRoot.listFiles();
        for (File file : subItems) {
            root.add(new DefaultMutableTreeNode(file));
        }
//        filesTree.setModel(model);
    }

    private String getLogAreaText() {
        String logAreaText = logArea.getText();
        if (logAreaText.equals("")) {
            return logAreaText;
        } else {
            return logAreaText.concat(System.lineSeparator());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MasterFrame masterFrame = new MasterFrame();
                masterFrame.setLocationRelativeTo(null);
                masterFrame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem closeProject;
    private javax.swing.JButton createModelButton;
    private javax.swing.JButton createPathPlanButton;
    private javax.swing.JMenuItem createProjectFileMenu;
    private javax.swing.JButton createRoboticArmInterfaceButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitFileMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JTree fileStructureTree;
    private javax.swing.JInternalFrame filesFrame;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPanel leftShortcuts;
    private javax.swing.JTextArea logArea;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JMenuItem openProjectFileMenu;
    private javax.swing.JButton predictClassifierButton;
    private javax.swing.JTable propertyWindow;
    private javax.swing.JMenuItem saveProjectFileMenu;
    private javax.swing.JButton testClassifierButton;
    private javax.swing.JPanel toolBar;
    private javax.swing.JMenu toolsMenu;
    private javax.swing.JButton trainClassifierButton;
    private javax.swing.JMenu viewMenu;
    private javax.swing.JPanel workspacePanel;
    // End of variables declaration//GEN-END:variables

    private void logText(String logText) {
        if (logArea.getText().equals("")) {
            logArea.setText(">>> " + logText);
        } else {
            logArea.append(System.lineSeparator() + ">>> " + logText);
        }
    }

    private void loadModelOnWorkspace() {
        modelIcon.setVisible(true);
        modelIcon.addMouseMotionListener(this);
        modelIcon.addMouseListener(this);
        modelIcon.addMouseListener(new ModelOptionsPopUpClickListener());

        workspacePanel.add(modelIcon);
        workspacePanel.revalidate();
        workspacePanel.repaint();
        logText("Model Added");
    }

    private void createModelOnWorkspace(HashMap<String, String> modelMap) {
        ImageIcon image = new ImageIcon(
                "/home/hashan/NetBeansProjects/FrameworkIDE/src/main/java/images/model-workspace-icon.png");
        modelIcon = new ClassifierModel(image);
        modelIcon.setVisible(true);
        modelIcon.setFigPath(modelMap.get("figPath"));
        modelIcon.setTiPath(modelMap.get("tiPath"));
        modelIcon.setOiPath(modelMap.get("oiPath"));
        modelIcon.setCfPath(modelMap.get("cfPath"));
        modelIcon.setPath(modelMap.get("path"));
        modelIcon.setName(modelMap.get("name"));

        modelIcon.addMouseListener(this);
        modelIcon.addMouseMotionListener(this);
        modelIcon.addMouseListener(new ModelOptionsPopUpClickListener());

        workspacePanel.add(modelIcon);
        workspacePanel.revalidate();
        workspacePanel.repaint();
        logText("Model Added");
    }

    @Override
    public void mouseDragged(MouseEvent me) {
        Point location = SwingUtilities.convertPoint(modelIcon, me.getPoint(), modelIcon.getParent());
        if (modelIcon.getParent().getBounds().contains(location)) {
            Point newLocation = modelIcon.getLocation();
            newLocation.translate(location.x - startPoint.x, location.y - startPoint.y);
            newLocation.x = Math.max(newLocation.x, 0);
            newLocation.x = Math.min(newLocation.x, modelIcon.getParent().getWidth() - modelIcon.getWidth());
            newLocation.y = Math.max(newLocation.y, 0);
            newLocation.y = Math.min(newLocation.y, modelIcon.getParent().getHeight() - modelIcon.getHeight());
            modelIcon.setLocation(newLocation);
            startPoint = location;
        }
    }

    @Override
    public void mouseMoved(MouseEvent me) {
    }

    @Override
    public void mouseClicked(MouseEvent me) {
        modelIcon.requestFocus(true);
        DefaultTableModel tableModel = (DefaultTableModel) propertyWindow.getModel();
        tableModel.setNumRows(0);
        tableModel.addRow(new Object[]{"Frozen Inference Graph", modelIcon.getFigPath()});
        tableModel.addRow(new Object[]{"Test Images Directory", modelIcon.getTiPath()});
        tableModel.addRow(new Object[]{"Output Directory", modelIcon.getOiPath()});
        tableModel.addRow(new Object[]{"Classes File", modelIcon.getCfPath()});
    }

    @Override
    public void mousePressed(MouseEvent me) {
        startPoint = SwingUtilities.convertPoint(modelIcon, me.getPoint(), modelIcon.getParent());
    }

    @Override
    public void mouseReleased(MouseEvent me) {
        startPoint = null;
    }

    @Override
    public void mouseEntered(MouseEvent me) {
    }

    @Override
    public void mouseExited(MouseEvent me) {
    }

    @Override
    public void run() {
        while (thread != null) {
            try {
                if (modelIcon != null) {
                    if (modelIcon.hasFocus()) {
                        modelIcon.setBorder(BorderFactory.createLineBorder(Color.GREEN, 2));
                    } else {
                        Point location = modelIcon.getLocation();
                        modelIcon.setBorder(BorderFactory.createLineBorder(Color.WHITE, 2));
                        modelIcon.setLocation(location);
                    }
                    enableTrainButtons(true);
                } else {
                    enableTrainButtons(false);
                }

                Thread.sleep(100);
            } catch (InterruptedException e) {
            }

        }
        thread = null;
    }

    public void start() {
        if (thread == null) {
            thread = new Thread(this);
            thread.start();
        }
    }

    public void stop() {
        thread = null;
    }

    private void enableTrainButtons(boolean value) {
        trainClassifierButton.setEnabled(value);
        testClassifierButton.setEnabled(value);
        predictClassifierButton.setEnabled(value);
    }

//    private void makeTree(String filePath){
//        if(!SystemVariables.isProjectCreated()){
//            return;
//        }
//        root = new DefaultMutableTreeNode(new File(filePath));
//        getList(root, new File(filePath));
//        filesFrame.setLayout(new BorderLayout());
//        tree = new JTree(root);
//        model = (DefaultTreeModel) tree.getModel();
//        tree.setRootVisible(false);
//        filesFrame.add(new JScrollPane((JTree)tree),"Center");
//    }
//    
//    private void updateTree(String rootPath){
//        if(tree != null){
//            DefaultTreeModel treeModel = (DefaultTreeModel) tree.getModel();
//            treeModel.reload(root);
//            tree.expandPath(tree.getSelectionPath());
//            filesFrame.removeAll();
//            filesFrame.add(new JScrollPane((JTree) tree), "Center");
//        } else {
//            makeTree("/home/hashan/FrameworkIDE");
//        }
//    }
//    
//    public void getList(DefaultMutableTreeNode node, File f) {
//        if(!f.isDirectory()) {
//            DefaultMutableTreeNode child = new DefaultMutableTreeNode(f);
//            node.add(child);   
//        } else {
//            DefaultMutableTreeNode child = new DefaultMutableTreeNode(f);
//            node.add(child);
//            File fList[] = f.listFiles();
//            for(int i = 0; i  < fList.length; i++)
//            getList(child, fList[i]);
//        }
//    }
    private void createModelFileInFolderStructure(HashMap<String, String> values) {

        try {

            DocumentBuilderFactory docFactory = DocumentBuilderFactory.newInstance();
            DocumentBuilder docBuilder = docFactory.newDocumentBuilder();

            // root elements
            Document doc = docBuilder.newDocument();
            Element rootElement = doc.createElement("classifier");
            doc.appendChild(rootElement);

            // model elements
            Element model = doc.createElement("model");
            rootElement.appendChild(model);

            // set attribute to model element
            Attr nameAttr = doc.createAttribute("name");
            nameAttr.setValue(values.get("name"));
            model.setAttributeNode(nameAttr);
            
            Attr pathAttr = doc.createAttribute("path");
            pathAttr.setValue(values.get("path"));
            model.setAttributeNode(pathAttr);

            // figPath elements
            Element figPath = doc.createElement("figPath");
            figPath.appendChild(doc.createTextNode(values.get("figPath")));
            model.appendChild(figPath);

            // tiPath elements
            Element tiPath = doc.createElement("tiPath");
            tiPath.appendChild(doc.createTextNode(values.get("tiPath")));
            model.appendChild(tiPath);

            // oiPath elements
            Element oiPath = doc.createElement("oiPath");
            oiPath.appendChild(doc.createTextNode(values.get("oiPath")));
            model.appendChild(oiPath);

            // cfPath elements
            Element cfpath = doc.createElement("cfPath");
            cfpath.appendChild(doc.createTextNode(values.get("cfPath")));
            model.appendChild(cfpath);

            // write the content into xml file
            TransformerFactory transformerFactory = TransformerFactory.newInstance();
            Transformer transformer = transformerFactory.newTransformer();
            DOMSource source = new DOMSource(doc);
            StreamResult result = new StreamResult(new File(values.get("path")));

            // Output to console for testing
            // StreamResult result = new StreamResult(System.out);
            transformer.transform(source, result);

            logText("Model saved!");

        } catch (ParserConfigurationException pce) {
            pce.printStackTrace();
        } catch (TransformerException tfe) {
            tfe.printStackTrace();
        }
//        fileStructureTree.getModel().valueForPathChanged(new TreePath(new File(SystemVariables.IDE_HOME_FOLDER)), "ClassiferModel.xml");
    }
}
